const ACTIONS={
    LOGIN:'LOGIN',
    GET_TOKEN:'GET_TOKEN',
    GET_USER:'GET_USER',
    ADD_TO_CART:' ADD_TO_CART',
    REMOVE_FROM_CART:' REMOVE_FROM_CART',
    ADJUST_QTY:'ADJUST_QTY',
    LOAD_CURRENT_ITEM:'LOAD_CURRENT_ITEM',
}


export default ACTIONS